/* Pokémon Rip and Go — the dex.
 *
 * Every creature in the game is in this file: what it looks like, what it is
 * made of, and what it can do in a fight. Nothing here is fetched, and no
 * image ships with the game — the art is typed out as letters, one character
 * per pixel, the way the rest of the demos in this folder do it. If you want
 * the creatures to look like something else, you do not edit this file: you
 * drop a PNG sheet into the Sprite Lab and point frames at species ids. See
 * sprites.js.
 *
 * ------------------------------------------------------------------ forms
 *
 * Sixteen body plans, 16x16 each, drawn facing RIGHT and mirrored by the game
 * when something faces the other way:
 *
 *     '.'        nothing — the background shows through
 *     '0'-'7'    an index into the species' palette
 *
 * Slot 0 is always the outline and slot 7 is always white, because at this
 * size a figure without a dark edge dissolves into whatever is behind it, and
 * an eye without a white in it is not an eye.
 *
 * --------------------------------------------------------------- species
 *
 * A species is a form, three colours, and some numbers. Three species to a
 * form, so sixteen drawings carry forty-eight creatures, and a shiny is the
 * same species with its hues turned. That is the whole trick, and it is why a
 * pack can hold something you have never seen without another 256 lines of
 * pixels being typed out for it.
 */
const Dex = (() => {
  'use strict';

  /* ================================================================ colour */
  /* Three colours per species, eight slots on the sprite. The other five are
   * worked out from the three, so every creature in the game is lit from the
   * same corner: highlight top left, shade bottom right. */

  const hex = (h) => [
    parseInt(h.slice(1, 3), 16),
    parseInt(h.slice(3, 5), 16),
    parseInt(h.slice(5, 7), 16),
  ];
  const str = (r, g, b) =>
    '#' + [r, g, b].map((v) => Math.max(0, Math.min(255, Math.round(v)))
      .toString(16).padStart(2, '0')).join('');

  function lighten(h, t) {
    const c = hex(h);
    return str(c[0] + (255 - c[0]) * t, c[1] + (255 - c[1]) * t, c[2] + (255 - c[2]) * t);
  }
  function darken(h, t) {
    const c = hex(h);
    return str(c[0] * (1 - t), c[1] * (1 - t), c[2] * (1 - t));
  }

  /* A shiny is not a second palette, it is this one turned. Cheap, and it
   * reads instantly as "that one is not the usual". */
  function spin(h, deg) {
    const c = hex(h).map((v) => v / 255);
    const max = Math.max(c[0], c[1], c[2]), min = Math.min(c[0], c[1], c[2]);
    const d = max - min;
    let hh = 0;
    if (d) {
      if (max === c[0]) hh = ((c[1] - c[2]) / d + 6) % 6;
      else if (max === c[1]) hh = (c[2] - c[0]) / d + 2;
      else hh = (c[0] - c[1]) / d + 4;
      hh *= 60;
    }
    const l = (max + min) / 2;
    const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
    hh = ((hh + deg) % 360 + 360) % 360;
    const ch = (1 - Math.abs(2 * l - 1)) * s;
    const x = ch * (1 - Math.abs((hh / 60) % 2 - 1));
    const m = l - ch / 2;
    const t = hh < 60 ? [ch, x, 0] : hh < 120 ? [x, ch, 0] : hh < 180 ? [0, ch, x]
      : hh < 240 ? [0, x, ch] : hh < 300 ? [x, 0, ch] : [ch, 0, x];
    return str((t[0] + m) * 255, (t[1] + m) * 255, (t[2] + m) * 255);
  }

  function palette(body, accent, belly, shinyDeg) {
    if (shinyDeg) {
      body = spin(body, shinyDeg);
      accent = spin(accent, shinyDeg + 50);
      belly = spin(belly, shinyDeg);
    }
    return [
      '#0b0d14',              // 0  outline
      body,                   // 1  body
      lighten(body, 0.30),    // 2  body, lit
      darken(body, 0.34),     // 3  body, shaded
      belly,                  // 4  belly and undersides
      accent,                 // 5  accent — horns, fins, markings
      lighten(accent, 0.38),  // 6  accent, lit
      '#ffffff',              // 7  the white of an eye
    ];
  }

  /* ================================================================= types */
  /* Eight, plus a ninth that only moves use. A move with no type of its own
   * is PLAIN and lands the same on everything, which is what makes TACKLE the
   * honest choice when you have no idea what you are looking at. */

  const TYPES = {
    EMBER: { name: 'EMBER', colour: '#ff7043', dark: '#40160c' },
    WAVE:  { name: 'WAVE',  colour: '#42a5f5', dark: '#0b2440' },
    LEAF:  { name: 'LEAF',  colour: '#66bb6a', dark: '#0e2c15' },
    SPARK: { name: 'SPARK', colour: '#ffd54f', dark: '#3a2d05' },
    FROST: { name: 'FROST', colour: '#80deea', dark: '#0c2f36' },
    STONE: { name: 'STONE', colour: '#a1887f', dark: '#2a1f1b' },
    GALE:  { name: 'GALE',  colour: '#b0bec5', dark: '#23303a' },
    SHADE: { name: 'SHADE', colour: '#9575cd', dark: '#241a3c' },
    PLAIN: { name: 'PLAIN', colour: '#cfd8dc', dark: '#262c33' },
  };

  const TYPE_LIST = ['EMBER', 'WAVE', 'LEAF', 'SPARK', 'FROST', 'STONE', 'GALE', 'SHADE'];

  /* What an attacking type does to a defending one. Anything not listed lands
   * at full price. */
  const STRONG = {
    EMBER: ['LEAF', 'FROST'],
    WAVE:  ['EMBER', 'STONE'],
    LEAF:  ['WAVE', 'STONE'],
    SPARK: ['WAVE', 'GALE'],
    FROST: ['LEAF', 'GALE'],
    STONE: ['EMBER', 'SPARK', 'FROST'],
    GALE:  ['LEAF', 'SHADE'],
    SHADE: ['STONE', 'SPARK'],
  };
  const WEAK = {
    EMBER: ['WAVE', 'STONE', 'EMBER'],
    WAVE:  ['LEAF', 'SPARK', 'WAVE'],
    LEAF:  ['EMBER', 'FROST', 'GALE', 'LEAF'],
    SPARK: ['LEAF', 'STONE', 'SPARK'],
    FROST: ['EMBER', 'STONE', 'FROST'],
    STONE: ['LEAF', 'WAVE', 'STONE'],
    GALE:  ['SPARK', 'FROST', 'STONE', 'GALE'],
    SHADE: ['GALE', 'EMBER', 'SHADE'],
  };

  function effect(atk, def) {
    if (atk === 'PLAIN') return 1;
    if ((STRONG[atk] || []).indexOf(def) >= 0) return 2;
    if ((WEAK[atk] || []).indexOf(def) >= 0) return 0.5;
    return 1;
  }

  /* ================================================================= moves */
  /* Two moves per type — the cheap one and the one a rare card knows — plus a
   * ladder of plain moves and five things that are not damage at all. */

  const TYPE_MOVES = {
    EMBER: ['SCORCH', 'FIRESTORM'],
    WAVE:  ['SPLASH', 'TIDAL CRASH'],
    LEAF:  ['VINE WHIP', 'BLOOM BURST'],
    SPARK: ['ZAP', 'THUNDERCLAP'],
    FROST: ['CHILL', 'BLIZZARD'],
    STONE: ['PEBBLE TOSS', 'ROCKFALL'],
    GALE:  ['GUST', 'CYCLONE'],
    SHADE: ['SHADOW NIP', 'NIGHTFALL'],
  };

  const PLAIN_MOVES = [
    { name: 'TACKLE', type: 'PLAIN', power: 42 },
    { name: 'SLAM', type: 'PLAIN', power: 58 },
    { name: 'CRUNCH', type: 'PLAIN', power: 70 },
    { name: 'BODY DROP', type: 'PLAIN', power: 82 },
  ];

  const UTILITY = {
    guard: { name: 'GUARD', type: 'PLAIN', power: 0, stat: 'def', by: 1, self: true,
      note: 'braces' },
    rally: { name: 'RALLY', type: 'PLAIN', power: 0, stat: 'atk', by: 1, self: true,
      note: 'winds up' },
    glare: { name: 'GLARE', type: 'PLAIN', power: 0, stat: 'atk', by: -1, self: false,
      note: 'stares down' },
    snare: { name: 'SNARE', type: 'PLAIN', power: 0, stat: 'spd', by: -1, self: false,
      note: 'tangles' },
    settle: { name: 'SETTLE', type: 'PLAIN', power: 0, heal: 0.34, self: true,
      note: 'catches its breath' },
  };

  /* Rarity decides how hard a card hits, how often it turns up, and what it
   * is worth when you tear it up instead of keeping it. */
  const RARITY = {
    common:   { key: 'common',   name: 'COMMON',    colour: '#b0bec5', total: 192, rip: 8 },
    uncommon: { key: 'uncommon', name: 'UNCOMMON',  colour: '#66bb6a', total: 228, rip: 24 },
    rare:     { key: 'rare',     name: 'RARE',      colour: '#42a5f5', total: 266, rip: 70 },
    epic:     { key: 'epic',     name: 'EPIC',      colour: '#ce93d8', total: 306, rip: 190 },
    legend:   { key: 'legend',   name: 'LEGENDARY', colour: '#ffd54f', total: 352, rip: 520 },
  };
  const RARITY_ORDER = ['common', 'uncommon', 'rare', 'epic', 'legend'];

  /* ================================================================= forms */

  const FORMS = {
    /* A blob. No front, no back, all belly. */
    slime: [
      '................',
      '................',
      '.....000000.....',
      '...0022222200...',
      '..022222222220..',
      '.02222222222220.',
      '.02227722772220.',
      '.02220722072220.',
      '.01111111111110.',
      '.01111111111110.',
      '.01144444444110.',
      '0114444444444110',
      '0144444444444410',
      '0144444444444410',
      '0011444444441100',
      '..000000000000..',
    ],

    /* Four legs, big ears, a snout. Faces right, like everything else here. */
    pup: [
      '................',
      '..........0000..',
      '.........055550.',
      '........05222250',
      '.......022222220',
      '.......022072220',
      '..00...022222220',
      '.0550..022222550',
      '.05502222222200.',
      '.00022222222220.',
      '..022222222220..',
      '..044444444440..',
      '..0440...04400..',
      '..0440...04400..',
      '..0440...04400..',
      '..000....0000...',
    ],

    /* Up on two legs, tail out behind, a crest it did not earn. */
    lizard: [
      '................',
      '..........550...',
      '.........05550..',
      '........0555000.',
      '.......022222200',
      '.......022072220',
      '.......022222220',
      '.000...022222200',
      '.05550.022222200',
      '.055500222222200',
      '..0550222222220.',
      '...000222444220.',
      '......022444220.',
      '......022200220.',
      '......044000440.',
      '......000...000.',
    ],

    /* Round, beaked, one wing showing and two feet under it. */
    bird: [
      '................',
      '.....0000000....',
      '....022222200...',
      '...02222222200..',
      '...0220722220550',
      '...0222222220550',
      '...022222222000.',
      '..0222222222220.',
      '..0223333332220.',
      '..0233333333220.',
      '..0223333332220.',
      '..0222222222220.',
      '...02222222220..',
      '....022222200...',
      '.....0500.0500..',
      '....05550.05550.',
    ],

    /* Domed back, six legs, feelers that arrive before it does. */
    bug: [
      '................',
      '....5......5....',
      '....05....50....',
      '.....05..50.....',
      '.....005500.....',
      '....00222200....',
      '...0220722200...',
      '..022222222220..',
      '..033322223330..',
      '..033322223330..',
      '..022222222220..',
      '..002222222200..',
      '.00.00000000.00.',
      '.0..0......0..0.',
      '................',
      '................',
    ],

    /* Fat in the middle, tail fin doing all the work. */
    fish: [
      '................',
      '.......55.......',
      '......0550......',
      '..55.05550......',
      '..5500555550....',
      '..5550022222000.',
      '..05500222207220',
      '..05502222222220',
      '..05504444442220',
      '..05504444422220',
      '..05500222222200',
      '..5550022222000.',
      '..5500555550....',
      '..55.05550......',
      '......0550......',
      '.......00.......',
    ],

    /* Two leaves, a seed for a body, no idea what is coming. */
    sprout: [
      '................',
      '...55.....55....',
      '..5665...5665...',
      '..56650.05665...',
      '...0665005660...',
      '.....055550.....',
      '......0550......',
      '....00222200....',
      '...0222222220...',
      '..0220722207220.',
      '..0222222222220.',
      '..0222222222220.',
      '..0444444444440.',
      '..0444444444440.',
      '...00444444400..',
      '.....000000.....',
    ],

    /* No feet. It trails off instead, which is worse. */
    ghost: [
      '................',
      '.....000000.....',
      '...0022222200...',
      '..022222222220..',
      '.02222222222220.',
      '.02207722077220.',
      '.02207722077220.',
      '.02222222222220.',
      '.02222222222220.',
      '.02222255522220.',
      '.02222222222220.',
      '.00222222222200.',
      '..002222222200..',
      '...00222222000..',
      '.....00000000...',
      '................',
    ],

    /* A block with arms. Nothing about it is soft. */
    golem: [
      '................',
      '...0000000000...',
      '..022222222220..',
      '..022222222220..',
      '..020772207720..',
      '..020772207720..',
      '..022222222220..',
      '0002222222222000',
      '0202333333332020',
      '0202333333332020',
      '0002333333332000',
      '..022222222220..',
      '..000222222000..',
      '....02200220....',
      '....04400440....',
      '....00000000....',
    ],

    /* Shell on top, head out the front, four stumps under the lot. */
    shell: [
      '................',
      '................',
      '.....000000.....',
      '...0055555500...',
      '..005666655500..',
      '.05566666555500.',
      '.05666666555500.',
      '.05555555555500.',
      '0005555555555000',
      '0022222222222220',
      '0022222222207220',
      '0002222222222200',
      '..0440...04400..',
      '..0440...04400..',
      '..000....0000...',
      '................',
    ],

    /* Wings wider than it is. Out at the hours nothing else keeps. */
    bat: [
      '................',
      '.....5....5.....',
      '....05....50....',
      '.00..055550..00.',
      '0330.022220.0330',
      '0333022072203330',
      '0333022222203330',
      '0333022222203330',
      '0033.044440.3300',
      '.000.004400.000.',
      '.....004400.....',
      '......0440......',
      '......0440......',
      '.......00.......',
      '................',
      '................',
    ],

    /* Coiled, with the head coming off the top of the coil. */
    serpent: [
      '................',
      '.........55.....',
      '........0550....',
      '.......022200...',
      '......02207220..',
      '......02222220..',
      '.....022222200..',
      '..00000222200...',
      '.022222202220...',
      '.0222000002220..',
      '.0220......0220.',
      '.0220.0000.0220.',
      '.02200222200220.',
      '.02222222222220.',
      '.00222222222200.',
      '..000000000000..',
    ],

    /* Wide, low, two claws up and a bad attitude. */
    crab: [
      '................',
      '..00........00..',
      '.0550......0550.',
      '.05500....00550.',
      '.05550....05550.',
      '..0550....0550..',
      '..000222222000..',
      '.02222222222220.',
      '.02207222072220.',
      '.02222222222220.',
      '0222222222222220',
      '0244444444444420',
      '.00444444444400.',
      '.0.0440..0440.0.',
      '.0..00....00..0.',
      '................',
    ],

    /* Patterned wings, furry body, drawn to anything lit. */
    moth: [
      '................',
      '.0000......0000.',
      '.05550....05550.',
      '056665....566650',
      '056665.00.566650',
      '0566500220056650',
      '0056502222056500',
      '.05650207205650.',
      '.05650222205650.',
      '.05665022056650.',
      '.05665044056650.',
      '..0565044056500.',
      '..0555044055500.',
      '...0000440000...',
      '.......00.......',
      '................',
    ],

    /* Legendary. Horns, jaw, and a wing behind the shoulder. */
    drake: [
      '....5...........',
      '...055....55....',
      '...055...0550...',
      '....05500555000.',
      '.....05555522220',
      '.5...02222222220',
      '055.022207222200',
      '0550222222222000',
      '0550222222222200',
      '05550222222220..',
      '055502224442220.',
      '.0550222444220..',
      '..00002222220...',
      '....000222.0220.',
      '......04400440..',
      '......000..000..',
    ],

    /* Legendary. Too big for the frame, which is the point. */
    titan: [
      '...0000000000...',
      '..055555555550..',
      '.05522222222550.',
      '0552207722022550',
      '0552207722022550',
      '0552222222222550',
      '0552255552222550',
      '0002222222222000',
      '0000222222220000',
      '0550022222200550',
      '0555033333305550',
      '0555033333305550',
      '0055033333300550',
      '..0044400444000.',
      '...04440.04440..',
      '...00000.00000..',
    ],
  };

  /* =============================================================== species */
  /* Three to a form. Name, colours, type, rarity, and how the rarity's points
   * get spread over HP / attack / defence / speed. */

  const SPECIES = [];

  function sp(name, form, body, accent, belly, type, rarity, bias, util, blurb) {
    const e = {
      id: name.toLowerCase().replace(/[^a-z0-9]/g, ''),
      no: SPECIES.length + 1,
      name, form, body, accent, belly, type, rarity, bias, util,
      blurb: blurb || '',
    };
    SPECIES.push(e);
    return e;
  }

  //  name          form      body       accent     belly      type     rarity      bias         utility
  sp('OOZLET',    'slime',  '#4fc3f7', '#ffffff', '#b3e5fc', 'WAVE',  'common',   [4, 2, 3, 2], 'guard');
  sp('TARBLOB',   'slime',  '#7e57c2', '#ce93d8', '#4a3670', 'SHADE', 'uncommon', [4, 3, 3, 2], 'glare');
  sp('GELDROP',   'slime',  '#80deea', '#ffffff', '#e0f7fa', 'FROST', 'rare',     [5, 3, 4, 2], 'settle');

  sp('CINDPUP',   'pup',    '#ff8a65', '#ffd54f', '#ffe0b2', 'EMBER', 'common',   [3, 4, 2, 3], 'rally');
  sp('VOLTPUP',   'pup',    '#ffd54f', '#fff59d', '#fff8e1', 'SPARK', 'uncommon', [3, 4, 2, 4], 'rally');
  sp('SNOWPUP',   'pup',    '#e0f7fa', '#80deea', '#ffffff', 'FROST', 'rare',     [3, 4, 3, 4], 'snare');

  sp('SCALION',   'lizard', '#66bb6a', '#ffeb3b', '#c5e1a5', 'LEAF',  'common',   [3, 4, 2, 3], 'rally');
  sp('MAGMLING',  'lizard', '#ef5350', '#ffa726', '#ffcc80', 'EMBER', 'uncommon', [3, 5, 2, 3], 'rally');
  sp('GRITSAUR',  'lizard', '#a1887f', '#d7ccc8', '#efebe9', 'STONE', 'rare',     [4, 5, 4, 2], 'guard');

  sp('PIPEEP',    'bird',   '#90caf9', '#ffb74d', '#ffffff', 'GALE',  'common',   [2, 3, 2, 5], 'snare');
  sp('EMBERBEAK', 'bird',   '#ff7043', '#ffca28', '#ffe0b2', 'EMBER', 'uncommon', [3, 4, 2, 5], 'rally');
  sp('STORMWING', 'bird',   '#5c6bc0', '#ffd54f', '#c5cae9', 'SPARK', 'rare',     [3, 5, 3, 5], 'glare');

  sp('NIBBUG',    'bug',    '#9ccc65', '#8d6e63', '#dcedc8', 'LEAF',  'common',   [2, 3, 4, 3], 'snare');
  sp('IRONMITE',  'bug',    '#90a4ae', '#cfd8dc', '#eceff1', 'STONE', 'uncommon', [3, 3, 5, 2], 'guard');
  sp('VOLTMITE',  'bug',    '#fdd835', '#424242', '#fff59d', 'SPARK', 'rare',     [3, 4, 4, 4], 'snare');

  sp('FINNIK',    'fish',   '#4dd0e1', '#ff8a65', '#e0f7fa', 'WAVE',  'common',   [3, 3, 3, 3], 'settle');
  sp('GLACIFIN',  'fish',   '#b3e5fc', '#4fc3f7', '#ffffff', 'FROST', 'uncommon', [3, 4, 3, 3], 'snare');
  sp('ABYSSFIN',  'fish',   '#5e35b1', '#00e5ff', '#311b92', 'SHADE', 'rare',     [4, 5, 3, 3], 'glare');

  sp('SEEDLET',   'sprout', '#aed581', '#8bc34a', '#f0f4c3', 'LEAF',  'common',   [3, 2, 3, 2], 'settle');
  sp('BLOOMLET',  'sprout', '#f48fb1', '#f06292', '#fce4ec', 'LEAF',  'uncommon', [3, 3, 3, 3], 'settle');
  sp('CACTIKIN',  'sprout', '#66bb6a', '#d7ccc8', '#a5d6a7', 'STONE', 'rare',     [4, 4, 4, 2], 'guard');

  sp('WISPLET',   'ghost',  '#b39ddb', '#ffffff', '#ede7f6', 'SHADE', 'common',   [2, 4, 2, 4], 'glare');
  sp('FOGWISP',   'ghost',  '#cfd8dc', '#80deea', '#eceff1', 'FROST', 'uncommon', [3, 4, 3, 4], 'snare');
  sp('HAUNTIS',   'ghost',  '#4527a0', '#ff5252', '#311b92', 'SHADE', 'rare',     [3, 5, 3, 5], 'glare');

  sp('PEBBLET',   'golem',  '#a1887f', '#8d6e63', '#d7ccc8', 'STONE', 'common',   [4, 3, 4, 1], 'guard');
  sp('CORELITH',  'golem',  '#6d4c41', '#ff7043', '#ffab91', 'EMBER', 'rare',     [5, 4, 5, 1], 'guard');
  sp('GEODON',    'golem',  '#546e7a', '#4dd0e1', '#b2ebf2', 'STONE', 'epic',     [5, 4, 6, 2], 'guard');

  sp('SHELLBY',   'shell',  '#4db6ac', '#8d6e63', '#b2dfdb', 'WAVE',  'common',   [4, 2, 5, 1], 'guard');
  sp('MOSSBACK',  'shell',  '#7cb342', '#33691e', '#c5e1a5', 'LEAF',  'uncommon', [4, 3, 5, 1], 'settle');
  sp('BOULDOME',  'shell',  '#8d6e63', '#a1887f', '#d7ccc8', 'STONE', 'rare',     [5, 3, 6, 1], 'guard');

  sp('SQUEEKER',  'bat',    '#9575cd', '#ce93d8', '#d1c4e9', 'SHADE', 'common',   [2, 4, 2, 4], 'glare');
  sp('GUSTFANG',  'bat',    '#78909c', '#eceff1', '#cfd8dc', 'GALE',  'uncommon', [3, 4, 2, 5], 'snare');
  sp('NIGHTVEIL', 'bat',    '#311b92', '#ffd54f', '#4527a0', 'SHADE', 'epic',     [4, 6, 3, 6], 'glare');

  sp('COILING',   'serpent', '#8bc34a', '#fdd835', '#dcedc8', 'LEAF',  'common',   [3, 4, 2, 3], 'snare');
  sp('EMBERCOIL', 'serpent', '#e53935', '#ffa000', '#ffcc80', 'EMBER', 'rare',     [4, 5, 3, 4], 'rally');
  sp('TIDECOIL',  'serpent', '#0288d1', '#4dd0e1', '#b3e5fc', 'WAVE',  'epic',     [5, 5, 4, 4], 'snare');

  sp('NIPPER',    'crab',   '#ef9a9a', '#e57373', '#ffcdd2', 'WAVE',  'common',   [3, 4, 3, 2], 'guard');
  sp('CINDERCLAW', 'crab',  '#d84315', '#ff8a65', '#ffab91', 'EMBER', 'uncommon', [3, 5, 3, 2], 'rally');
  sp('GLACICLAW', 'crab',   '#4fc3f7', '#e1f5fe', '#b3e5fc', 'FROST', 'rare',     [4, 5, 4, 2], 'guard');

  sp('FLUTTIK',   'moth',   '#fff9c4', '#ffb74d', '#fffde7', 'GALE',  'common',   [2, 3, 2, 4], 'snare');
  sp('DUSKMOTH',  'moth',   '#5c6bc0', '#7e57c2', '#9fa8da', 'SHADE', 'uncommon', [3, 4, 2, 5], 'glare');
  sp('AURORAMOTH', 'moth',  '#80deea', '#f48fb1', '#e0f7fa', 'FROST', 'epic',     [4, 5, 3, 6], 'snare');

  sp('EMBERDRAKE', 'drake', '#e64a19', '#ffc107', '#ffcc80', 'EMBER', 'epic',     [5, 6, 4, 4],
    'rally', 'Hatched in a vent. Has never once been cold.');
  sp('STORMDRAKE', 'drake', '#3949ab', '#ffeb3b', '#c5cae9', 'SPARK', 'legend',   [5, 6, 4, 6],
    'glare', 'The weather does what it is told.');
  sp('VOIDDRAKE',  'drake', '#1a1a2e', '#7c4dff', '#4527a0', 'SHADE', 'legend',   [5, 7, 4, 5],
    'glare', 'Older than the box you keep it in.');

  sp('STONETITAN', 'titan', '#795548', '#a1887f', '#d7ccc8', 'STONE', 'epic',     [6, 5, 6, 1],
    'guard', 'Sat down once. The hill is still there.');
  sp('TIDETITAN',  'titan', '#01579b', '#4fc3f7', '#b3e5fc', 'WAVE',  'legend',   [7, 5, 6, 2],
    'settle', 'Comes in twice a day whether you are ready or not.');
  sp('SUNTITAN',   'titan', '#ff8f00', '#fff176', '#ffe082', 'EMBER', 'legend',   [6, 6, 5, 3],
    'rally', 'Stands where the light does.');

  /* ================================================================ lookup */

  const BY_ID = {};
  SPECIES.forEach((s) => { BY_ID[s.id] = s; });

  const POOLS = {};
  RARITY_ORDER.forEach((r) => { POOLS[r] = SPECIES.filter((s) => s.rarity === r); });

  function stats(sp) {
    const w = sp.bias, sum = w[0] + w[1] + w[2] + w[3];
    const t = RARITY[sp.rarity].total;
    return {
      hp: Math.round(t * w[0] / sum) + 18,
      atk: Math.round(t * w[1] / sum) + 8,
      def: Math.round(t * w[2] / sum) + 8,
      spd: Math.round(t * w[3] / sum) + 8,
    };
  }

  /* Three moves, worked out from what the creature is rather than listed by
   * hand — a rare knows the big version of its type's move, everything knows
   * something plain, and the third slot is the one bit of character. */
  function moves(sp) {
    const tier = RARITY_ORDER.indexOf(sp.rarity);
    const plain = PLAIN_MOVES[tier <= 0 ? 0 : tier <= 2 ? 1 : tier === 3 ? 2 : 3];
    const names = TYPE_MOVES[sp.type];
    const big = tier >= 2;
    const typed = { name: names[big ? 1 : 0], type: sp.type, power: big ? 74 : 48 };
    return [typed, plain, UTILITY[sp.util] || UTILITY.guard];
  }

  function paletteFor(sp, shiny) {
    return palette(sp.body, sp.accent, sp.belly, shiny ? 150 : 0);
  }

  /* ============================================================== the check */
  /* Every form has to be 16 rows of 16. A row one character short shifts the
   * whole creature and is nearly impossible to spot by eye, so it gets said
   * out loud in the console instead of waiting to be found in a booster pack. */
  function validate() {
    const bad = [];
    Object.keys(FORMS).forEach((k) => {
      const f = FORMS[k];
      if (f.length !== 16) bad.push(k + ': ' + f.length + ' rows, want 16');
      f.forEach((row, i) => {
        if (row.length !== 16) bad.push(k + ' row ' + i + ': ' + row.length + ' wide — "' + row + '"');
        if (/[^0-7.]/.test(row)) bad.push(k + ' row ' + i + ': stray character — "' + row + '"');
      });
    });
    SPECIES.forEach((s) => {
      if (!FORMS[s.form]) bad.push(s.name + ': no form called ' + s.form);
      if (!TYPES[s.type]) bad.push(s.name + ': no type called ' + s.type);
      if (!RARITY[s.rarity]) bad.push(s.name + ': no rarity called ' + s.rarity);
    });
    if (bad.length) console.error('Dex: ' + bad.length + ' problem(s)\n' + bad.join('\n'));
    return bad;
  }

  return {
    TYPES, TYPE_LIST, FORMS, SPECIES, RARITY, RARITY_ORDER, UTILITY,
    byId: (id) => BY_ID[id],
    pool: (r) => POOLS[r] || [],
    effect, stats, moves, paletteFor, palette, lighten, darken, spin, validate,
  };
})();

Dex.validate();
